In [32]:
import numpy as np
np.set_printoptions(suppress= True, precision= 4)

# 1. Generate the Temperature Data

In [43]:
np.random.seed(42)
temperature_celsuis = np.random.normal( loc = 13, scale = 8, size = 365)

In [44]:
temperature_celsuis.shape

(365,)

In [45]:
temperature_celsuis[:15] # as we will see there are some values in negative temperature 

array([16.9737, 11.8939, 18.1815, 25.1842, 11.1268, 11.1269, 25.6337,
       19.1395,  9.2442, 17.3405,  9.2927,  9.2742, 14.9357, -2.3062,
       -0.7993])

# 2. Clean the Data with `np.where`

In [46]:
#replacing the negative values with 0 and keeping the rest same
temperature_celsuis = np.where(temperature_celsuis < 0, 0, temperature_celsuis)

In [47]:
temperature_celsuis[:15]

array([16.9737, 11.8939, 18.1815, 25.1842, 11.1268, 11.1269, 25.6337,
       19.1395,  9.2442, 17.3405,  9.2927,  9.2742, 14.9357,  0.    ,
        0.    ])

# 3. Convert to Fahrenheit (Unary ufuncs)

In [48]:
temperature_fahrenheit = temperature_celsuis * (9/5) + 32

In [49]:
temperature_fahrenheit[:15] 

array([62.5527, 53.409 , 64.7267, 77.3316, 52.0282, 52.0284, 78.1407,
       66.4511, 48.6396, 63.2129, 48.7268, 48.6935, 58.8843, 32.    ,
       32.    ])

# 4. Calculate Heat Index (Binary ufuncs)

In [50]:
np.random.seed(42)
humidity = np.random.uniform(low = 0.4, high = 0.9, size = 365) #use shift + Tab for viewing what a particular method can do

In [51]:
heat_index = temperature_fahrenheit + (humidity * 10)

In [ ]:
'''
Even though the humidity is a positive number in our case but it can become negative due to some sensor glitches.
That's why we have used the np.maximum() to choose the greater number between heat index and temperature
So even if the humidity or heat index formula changes or the sensor glitches the heat_index will always be greater or 
equal to the temperature 
in this case it seems useless because we know that all the elements of the heat index are greater then the temperature 
by +(humidity * 10) 

'''
heat_index = np.maximum(heat_index, temperature_fahrenheit)

In [53]:
heat_index

array([ 68.4254,  62.1626,  72.3867,  84.3249,  56.8083,  56.8084,
        82.4311,  74.7819,  55.6451,  70.7532,  52.8297,  57.543 ,
        67.0465,  37.0617,  36.9091,  52.2201,  46.3364,  66.5489,
        48.4842,  40.519 ,  83.5646,  56.8463,  61.8331,  40.7154,
        53.8412,  64.9232,  43.8241,  67.3812,  53.7129,  55.4319,
        53.7731,  86.9254,  59.5309,  48.9134,  76.0728,  45.8618,
        63.9307,  36.4884,  43.6953,  64.4356,  70.6441,  64.3436,
        57.9066,  59.6107,  39.4032,  52.3469,  54.3254,  77.2229,
        67.0817,  36.9243,  68.9147,  57.7305,  54.3498,  72.6823,
        77.2359,  77.4198,  47.7577,  55.9273,  64.3963,  75.0745,
        54.4433,  58.0833,  47.6125,  43.9584,  72.505 ,  81.6433,
        59.0677,  77.8619,  64.9803,  55.0447,  68.4653,  82.5413,
        58.9117,  86.0082,  39.5343,  74.8804,  64.5098,  55.4645,
        62.5137,  36.5793,  60.5522,  67.6589,  82.3362,  52.2547,
        49.3126,  53.8006,  76.2298,  67.3218,  56.2075,  69.1