In [1]:
import numpy as np
np.set_printoptions(suppress = True, precision = 4)

In [2]:
sales_data_list = [
  [    1001,        1,        1,        2,    85000,    75000,       25,        0,        0,      501],
  [    1002,        0,        0,        1,   150000,   135000,       25,        1,        0,      502],
  [    1003,        2,        2,        5,    15000,    12000,       26,        2,      0.1,      503],
  [    1004,        3,        2,       10,     2500,     2000,       26,        0,     0.15,      501],
  [    1005,        1,        1,        1,    90000,    80000,       27,        1,        0,      504],
  [    1006,        0,        0,        1,   155000,   138000,       27,        2,        0,      505],
  [    1007,        2,        2,        8,    14000,    11500,       28,        0,      0.1,      506],
  [    1008,        1,        1,        3,    88000,    78000,       28,        1,     0.05,      502],
  [    1009,        0,        0,        2,   148000,   132000,       29,        2,        0,      507],
  [    1010,        2,        2,        4,    15500,    12500,       29,        0,      0.1,      503],
  [    1011,        3,        2,       12,     2400,     1900,       30,        1,     0.15,      508],
  [    1012,        1,        1,        1,    92000,    81000,       30,        2,        0,      504],
  [    1013,        0,        0,        1,   160000,   142000,       31,        0,        0,      509],
  [    1014,        2,        2,        6,    14500,    11800,       31,        1,      0.1,      505],
  [    1015,        1,        1,        2,    86000,    76000,       32,        2,     0.05,      510],
  [    1016,        3,        2,       15,     2300,     1800,       32,        0,      0.2,      506],
  [    1017,        0,        0,        1,   152000,   136000,       33,        1,        0,      511],
  [    1018,        1,        1,        1,    89000,    79000,       33,        2,        0,      507],
  [    1019,        2,        2,        7,    13000,    11000,       34,        0,      0.1,      508],
  [    1020,        0,        0,        3,   150000,   135000,       34,        1,     0.05,      512],
  [    1021,        1,        1,        2,    91000,    80500,       35,        2,        0,      509],
  [    1022,        2,        2,        3,    16000,    13000,       35,        0,        0,      510],
  [    1023,        3,        2,        9,     2600,     2100,       36,        1,     0.15,      513],
  [    1024,        0,        0,        1,   158000,   140000,       36,        2,        0,      511],
  [    1025,        1,        1,        1,    84000,    74000,       37,        0,        0,      514],
  [    1026,        2,        2,        5,    14000,    11500,       37,        1,      0.1,      512],
  [    1027,        0,        0,        2,   145000,   130000,       38,        2,        0,      515],
  [    1028,        1,        1,        4,    87000,    77000,       38,        0,     0.05,      513],
  [    1029,        3,        2,       11,     2500,     2000,       39,        1,     0.15,      516],
  [    1030,        2,        2,        6,    15000,    12000,       39,        2,      0.1,      514],
  [    1031,        0,        0,        1,   162000,   145000,       40,        0,        0,      517],
  [    1032,        1,        1,        1,    93000,    82000,       40,        1,        0,      515],
  [    1033,        2,        2,        8,    13500,    11200,       41,        2,      0.1,      518],
  [    1034,        0,        0,        2,   155000,   138000,       41,        0,     0.05,      516],
  [    1035,        1,        1,        3,    89500,    79500,       42,        1,        0,      519],
  [    1036,        3,        2,       14,     2350,     1850,       42,        2,      0.2,      517],
  [    1037,        2,        2,        4,    15800,    12800,       43,        0,      0.1,      520],
  [    1038,        0,        0,        1,   149000,   133000,       43,        1,        0,      518],
  [    1039,        1,        1,        1,    90500,    80000,       44,        2,        0,      521],
  [    1040,        2,        2,        7,    14200,    11600,       44,        0,      0.1,      519],
  [    1041,        0,        0,        1,   153000,   137000,       45,        1,        0,      522],
  [    1042,        1,        1,        2,    88500,    78500,       45,        2,     0.05,      520],
  [    1043,        3,        2,       10,     2550,     2050,       46,        0,     0.15,      523],
  [    1044,        2,        2,        6,    15100,    12100,       46,        1,      0.1,      521],
  [    1045,        0,        0,        2,   159000,   141000,       47,        2,        0,      524],
  [    1046,        1,        1,        1,    92500,    81500,       47,        0,        0,      522],
  [    1047,        2,        2,        9,    13800,    11400,       48,        1,      0.1,      525],
  [    1048,        0,        0,        1,   161000,   144000,       48,        2,        0,      523],
  [    1049,        1,        1,        3,    87500,    77500,       49,        0,     0.05,      526],
  [    1050,        3,        2,       13,     2450,     1950,       49,        1,      0.2,      524],
  [    1051,        2,        2,        5,    14800,    11900,       50,        2,      0.1,      527],
  [    1052,        0,        0,        1,   156000,   139000,       50,        0,        0,      525],
  [    1053,        1,        1,        1,    94000,    83000,       51,        1,        0,      528],
  [    1054,        2,        2,        8,    12800,    10800,       51,        2,      0.1,      526],
  [    1055,        0,        0,        2,   151000,   135000,       52,        0,     0.05,      529]
]

# 1. First Look: Data Loading & Inspection<b>

### Load the data into a NumPy array and get a feel for its structure.


 1. Convert 'sales_data_list' into 'sales_arr'. <b>
 2. Print the array's .shape and .dtype

In [3]:
sales_data_array = np.array(sales_data_list)

In [4]:
sales_data_array.shape

(55, 10)

In [5]:
sales_data_array.ndim

2

In [6]:
sales_data_array.dtype

dtype('float64')

In [7]:
sales_data_array[:5]  #printing the first five rows of sale-data

array([[  1001.  ,      1.  ,      1.  ,      2.  ,  85000.  ,  75000.  ,
            25.  ,      0.  ,      0.  ,    501.  ],
       [  1002.  ,      0.  ,      0.  ,      1.  , 150000.  , 135000.  ,
            25.  ,      1.  ,      0.  ,    502.  ],
       [  1003.  ,      2.  ,      2.  ,      5.  ,  15000.  ,  12000.  ,
            26.  ,      2.  ,      0.1 ,    503.  ],
       [  1004.  ,      3.  ,      2.  ,     10.  ,   2500.  ,   2000.  ,
            26.  ,      0.  ,      0.15,    501.  ],
       [  1005.  ,      1.  ,      1.  ,      1.  ,  90000.  ,  80000.  ,
            27.  ,      1.  ,      0.  ,    504.  ]])

# 2. Profit Calculation: Vectorized Arithmetic<b>

### Calculate the total profit for each order line item.
    
1. Calculate total profit: (SalePrice - CostPrice) * UnitsSold.
    <b>
2. Print the first 5 profit values.

In [8]:
#we have the total profit formula above, but we don't know the which columns is which
#so first we will look into the assignment html for the column reference
# Col 4: SalePrice
# Col 5: CostPrice
# Col 3: UnitsSold   #note that the columns are indexed in pythonic way like starting from zero

In [9]:
SalesPrice = sales_data_array[:,4] #the sales price column we have sliced it
CostPrice = sales_data_array[:,5]
UnitSold  = sales_data_array[:,3] #you can always use the indexed version instead of creating new variables.

In [10]:
#now to calculate the Total Profit
TotalProfit = (SalesPrice - CostPrice) * UnitSold

In [11]:
TotalProfit[:5] #first five rows of the TotalProfit

array([20000., 15000., 15000.,  5000., 10000.])

In [12]:
#you can also use the following code directly if you don't want to create new variables.
# TotalProfit = (sales_data_array[:,4] - sales_data_array[:,5]) * sales_data_array[:,3]

# The above code will have the same result as the previous one, the previous one is just a bit clearer

# 3. High-Value Orders: Boolean Indexing
### Isolate orders where more than 5 units were sold.
1. Create a boolean mask where UnitsSold > 5.
<b> 
2. Use it to select the high-value orders.
<b>
3. Print the shape of the resulting array.

In [13]:
UnitSold_mask = sales_data_array[:,3] > 5 #this creates an array that contains the True/False values 

# The true/false values are results of instances that meets the criteria we defined 
# the bolean mask i.e the true/false array is used to filter out the instances 
# instead of using for loops and if logics we use simple numpy indexing and some criterias
# this is very fast and intuitive 
# in this example our goal is to find out the orders that have sold units more than 5.

In [14]:
print(np.sum(UnitSold_mask)) #to find out the number of instance where sold unit is greater than 5

17


In [15]:
high_value_orders = sales_data_array[UnitSold_mask]

In [16]:
high_value_orders #these are the orders that contains the Unit sold more than 5

array([[ 1004.  ,     3.  ,     2.  ,    10.  ,  2500.  ,  2000.  ,
           26.  ,     0.  ,     0.15,   501.  ],
       [ 1007.  ,     2.  ,     2.  ,     8.  , 14000.  , 11500.  ,
           28.  ,     0.  ,     0.1 ,   506.  ],
       [ 1011.  ,     3.  ,     2.  ,    12.  ,  2400.  ,  1900.  ,
           30.  ,     1.  ,     0.15,   508.  ],
       [ 1014.  ,     2.  ,     2.  ,     6.  , 14500.  , 11800.  ,
           31.  ,     1.  ,     0.1 ,   505.  ],
       [ 1016.  ,     3.  ,     2.  ,    15.  ,  2300.  ,  1800.  ,
           32.  ,     0.  ,     0.2 ,   506.  ],
       [ 1019.  ,     2.  ,     2.  ,     7.  , 13000.  , 11000.  ,
           34.  ,     0.  ,     0.1 ,   508.  ],
       [ 1023.  ,     3.  ,     2.  ,     9.  ,  2600.  ,  2100.  ,
           36.  ,     1.  ,     0.15,   513.  ],
       [ 1029.  ,     3.  ,     2.  ,    11.  ,  2500.  ,  2000.  ,
           39.  ,     1.  ,     0.15,   516.  ],
       [ 1030.  ,     2.  ,     2.  ,     6.  , 15000.  , 12000.

In [17]:
high_value_orders.shape

(17, 10)

# 4. Smartphone Sales Stats: Combining Masks <b>

### Find the average sale price for smartphones in the Central region.<b>
 
1. Create masks for ProductID == 1 and RegionID == 2.<b> 

2. Combine them with '&'.<b> 

3. Use the mask to get the SalePrice and find its mean.<b> 
 
Col 1: ProductID (0: Laptop, 1: Smartphone, 2: Headphones, 3: Charger)

Col 7: RegionID (0: North, 1: South, 2: Central)

In [18]:
smartphones = sales_data_array[:,1] == 1  
central_region = sales_data_array[:,7] == 2

In [19]:
smartphones_sales = smartphones & central_region
#this will create a new bolean mask of True/false 
#there will only be a true value if in both of the above have a true on the same instance

In [20]:
smartphones_central_sales = sales_data_array[smartphones_sales]

#this will create an array of a filtered sales_data that will contain the smartphones sales in centeral region only
smartphones_central_sales

array([[ 1012.  ,     1.  ,     1.  ,     1.  , 92000.  , 81000.  ,
           30.  ,     2.  ,     0.  ,   504.  ],
       [ 1015.  ,     1.  ,     1.  ,     2.  , 86000.  , 76000.  ,
           32.  ,     2.  ,     0.05,   510.  ],
       [ 1018.  ,     1.  ,     1.  ,     1.  , 89000.  , 79000.  ,
           33.  ,     2.  ,     0.  ,   507.  ],
       [ 1021.  ,     1.  ,     1.  ,     2.  , 91000.  , 80500.  ,
           35.  ,     2.  ,     0.  ,   509.  ],
       [ 1039.  ,     1.  ,     1.  ,     1.  , 90500.  , 80000.  ,
           44.  ,     2.  ,     0.  ,   521.  ],
       [ 1042.  ,     1.  ,     1.  ,     2.  , 88500.  , 78500.  ,
           45.  ,     2.  ,     0.05,   520.  ]])

In [21]:
#now the mean of the sale price in the central region for smartphone
mean_price = np.mean(smartphones_central_sales[:,4])
print(mean_price)

89500.0


# 5. Top Seller: Statistical Methods <b>
### Find the OrderID of the transaction with the highest revenue.<b>
 1. Calculate revenue (UnitsSold * SalePrice). <b>
 2. Find the index of the max value with .argmax(). <b>
 3. Use the index to get the OrderID.
    

In [22]:
#So basically we have to find the order that have generated the most revenue
#that's why we need the 1. Revenue, 2. The index number of the row with highest Revenue and 3. The order Id

revenue = (UnitSold * SalesPrice) #these variables have been defined in previous tasks

In [24]:
revenue[:5] #top five values of revenue

array([170000., 150000.,  75000.,  25000.,  90000.])

In [26]:
revenue.shape

(55,)

In [27]:
revenue.argmax() #this will give us the index number with the maximum revenue

19

In [29]:
sales_data_array[19,:] #this will give us the 20th row with index number 19

array([  1020.  ,      0.  ,      0.  ,      3.  , 150000.  , 135000.  ,
           34.  ,      1.  ,      0.05,    512.  ])

In [31]:
#as the orderID column is the first one so we can write
sales_data_array[19,0] # 20th row with index number 19 and first column(orderID)

1020.0

# 6. Discount Impact: Modifying with Slicing <b>
### Apply a 5% discount to all Laptop sales. <b>

 1. Create a mask for laptop sales (ProductID == 0).<b>
 2. Select the 'Discount' column for those sales.<b>
 3. Set their value to 0.05.

In [38]:
laptop_mask = sales_data_array[:,1] == 0

In [40]:
laptop_mask.shape

(55,)

In [41]:
laptop_sales = sales_data_array[laptop_mask] #this will give an array which will contain only laptop sales

#you can also use {laptops_sales = sales_data_array[(sales_data_array[:,1] == 0) ]} instead of intermediate steps

In [36]:
laptop_sales

array([[  1002.  ,      0.  ,      0.  ,      1.  , 150000.  , 135000.  ,
            25.  ,      1.  ,      0.  ,    502.  ],
       [  1006.  ,      0.  ,      0.  ,      1.  , 155000.  , 138000.  ,
            27.  ,      2.  ,      0.  ,    505.  ],
       [  1009.  ,      0.  ,      0.  ,      2.  , 148000.  , 132000.  ,
            29.  ,      2.  ,      0.  ,    507.  ],
       [  1013.  ,      0.  ,      0.  ,      1.  , 160000.  , 142000.  ,
            31.  ,      0.  ,      0.  ,    509.  ],
       [  1017.  ,      0.  ,      0.  ,      1.  , 152000.  , 136000.  ,
            33.  ,      1.  ,      0.  ,    511.  ],
       [  1020.  ,      0.  ,      0.  ,      3.  , 150000.  , 135000.  ,
            34.  ,      1.  ,      0.05,    512.  ],
       [  1024.  ,      0.  ,      0.  ,      1.  , 158000.  , 140000.  ,
            36.  ,      2.  ,      0.  ,    511.  ],
       [  1027.  ,      0.  ,      0.  ,      2.  , 145000.  , 130000.  ,
            38.  ,      2.  ,      0.

In [44]:
#now to apply the discount 0.5 to all laptop sales
#as the discount column is the 9th column i.e with index 8 so we will use it

laptop_sales[:,8] = 0.5 

In [45]:
laptop_sales

array([[  1002. ,      0. ,      0. ,      1. , 150000. , 135000. ,
            25. ,      1. ,      0.5,    502. ],
       [  1006. ,      0. ,      0. ,      1. , 155000. , 138000. ,
            27. ,      2. ,      0.5,    505. ],
       [  1009. ,      0. ,      0. ,      2. , 148000. , 132000. ,
            29. ,      2. ,      0.5,    507. ],
       [  1013. ,      0. ,      0. ,      1. , 160000. , 142000. ,
            31. ,      0. ,      0.5,    509. ],
       [  1017. ,      0. ,      0. ,      1. , 152000. , 136000. ,
            33. ,      1. ,      0.5,    511. ],
       [  1020. ,      0. ,      0. ,      3. , 150000. , 135000. ,
            34. ,      1. ,      0.5,    512. ],
       [  1024. ,      0. ,      0. ,      1. , 158000. , 140000. ,
            36. ,      2. ,      0.5,    511. ],
       [  1027. ,      0. ,      0. ,      2. , 145000. , 130000. ,
            38. ,      2. ,      0.5,    515. ],
       [  1031. ,      0. ,      0. ,      1. , 162000. , 145000

In [46]:
#now as the modification of a slice is the modification of the main array lets see the main array

sales_data_array #now we can see alot of discount column have 0.

array([[  1001.  ,      1.  ,      1.  ,      2.  ,  85000.  ,  75000.  ,
            25.  ,      0.  ,      0.  ,    501.  ],
       [  1002.  ,      0.  ,      0.  ,      1.  , 150000.  , 135000.  ,
            25.  ,      1.  ,      0.  ,    502.  ],
       [  1003.  ,      2.  ,      2.  ,      5.  ,  15000.  ,  12000.  ,
            26.  ,      2.  ,      0.1 ,    503.  ],
       [  1004.  ,      3.  ,      2.  ,     10.  ,   2500.  ,   2000.  ,
            26.  ,      0.  ,      0.15,    501.  ],
       [  1005.  ,      1.  ,      1.  ,      1.  ,  90000.  ,  80000.  ,
            27.  ,      1.  ,      0.  ,    504.  ],
       [  1006.  ,      0.  ,      0.  ,      1.  , 155000.  , 138000.  ,
            27.  ,      2.  ,      0.  ,    505.  ],
       [  1007.  ,      2.  ,      2.  ,      8.  ,  14000.  ,  11500.  ,
            28.  ,      0.  ,      0.1 ,    506.  ],
       [  1008.  ,      1.  ,      1.  ,      3.  ,  88000.  ,  78000.  ,
            28.  ,      1.  ,      0.